name: cellprofiler_analysis
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10.6
  - pandas=1.5.1
  - numpy=1.23.4
  - matplotlib=3.6.2
  - seaborn=0.12.1
  - scipy=1.9.3
  - jupyter=1.0.0
  - ipykernel=6.17.1
  - umap-learn=0.5.3
  - scikit-learn=1.1.3
  - tqdm=4.64.1
  - plotly=5.11.0
  - pathlib=1.0.1
  - pip
  - pip:
    - pycytominer